// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// load_spm
S4 load_spm(CharacterVector file);
RcppExport SEXP wspaces_load_spm(SEXP fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type file(fileSEXP);
    rcpp_result_gen = Rcpp::wrap(load_spm(file));
    return rcpp_result_gen;
END_RCPP
}
// cooc_to_pmi
S4 cooc_to_pmi(SEXP m_, bool ppmi, bool ow);
RcppExport SEXP wspaces_cooc_to_pmi(SEXP m_SEXP, SEXP ppmiSEXP, SEXP owSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type m_(m_SEXP);
    Rcpp::traits::input_parameter< bool >::type ppmi(ppmiSEXP);
    Rcpp::traits::input_parameter< bool >::type ow(owSEXP);
    rcpp_result_gen = Rcpp::wrap(cooc_to_pmi(m_, ppmi, ow));
    return rcpp_result_gen;
END_RCPP
}
// tfidf_weight
NumericMatrix tfidf_weight(NumericMatrix m_, NumericVector df_, int mode, bool ow);
RcppExport SEXP wspaces_tfidf_weight(SEXP m_SEXP, SEXP df_SEXP, SEXP modeSEXP, SEXP owSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m_(m_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df_(df_SEXP);
    Rcpp::traits::input_parameter< int >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< bool >::type ow(owSEXP);
    rcpp_result_gen = Rcpp::wrap(tfidf_weight(m_, df_, mode, ow));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"wspaces_load_spm", (DL_FUNC) &wspaces_load_spm, 1},
    {"wspaces_cooc_to_pmi", (DL_FUNC) &wspaces_cooc_to_pmi, 3},
    {"wspaces_tfidf_weight", (DL_FUNC) &wspaces_tfidf_weight, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_wspaces(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
