# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importClassesFrom Matrix dgTMatrix
load_spm <- function(file) {
    .Call('wspaces_load_spm', PACKAGE = 'wspaces', file)
}

cooc_to_pmi <- function(m_, ppmi = TRUE, ow = TRUE) {
    .Call('wspaces_cooc_to_pmi', PACKAGE = 'wspaces', m_, ppmi, ow)
}

tfidf_weight <- function(m_, df_, mode = 1L, ow = FALSE) {
    .Call('wspaces_tfidf_weight', PACKAGE = 'wspaces', m_, df_, mode, ow)
}

